In [ ]:
#Numpy

In [ ]:
#1. Create a numpy array with numpy.array module with data type integer and float

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5], dtype = 'int')
print(arr1)

[1 2 3 4 5]


In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
arr2 = np.array([1.3, 2.3, 3, 4,5.0], dtype = 'float')
print(arr2)

[1.3 2.3 3.  4.  5. ]


In [ ]:
arr2.dtype

dtype('float64')

In [ ]:
#2. Create numpy arrays that have zeros, one, two, three, four dimensions respectively. Also, print the shape and dimensions of the numpy arrays created above

In [ ]:
#Zero_dimension
a0= np.array(5)
print(a0)
print(a0.ndim)
print(a0.shape)

5
0
()


In [ ]:
#One_dimension
a1= np.array([1,2,3,4])
print(a1)
print(a1.ndim)
print(a1.shape)   #shape is total number of elements present

[1 2 3 4]
1
(4,)


In [ ]:
#Two_dimension
a2= np.array([[1,2,3], [3,5,8]])
print(a2)
print(a2.ndim)
print(a2.shape)

[[1 2 3]
 [3 5 8]]
2
(2, 3)


In [ ]:
#Three_dimension
a3= np.array([[[1,2], [3,5]], [[7,8], [7,8]]])
print(a3)
print(a3.ndim)
print(a3.shape)

[[[1 2]
  [3 5]]

 [[7 8]
  [7 8]]]
3
(2, 2, 2)


In [ ]:
#Four_dimension
a4= np.array([[[[1,2], [3,5]], [[7,8], [7,8]]]])
print(a4)
print(a4.ndim)
print(a4.shape)

[[[[1 2]
   [3 5]]

  [[7 8]
   [7 8]]]]
4
(1, 2, 2, 2)


In [ ]:
#3. Create a 2x2, 3x3, and 4x4 identity matrix numoy
- Use identity() or eye()

In [ ]:
np.identity(2, dtype = int)  #identity matriz = diagonal elements are all 1, and the remaining elements are all 0

array([[1, 0],
       [0, 1]])

In [ ]:
np.identity(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.identity(4, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
#eye() -  allows you to cutomize identity matrix
np.eye(4,4, dtype = 'int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
#but if we want
np.eye(2,4, dtype = 'int')    #but it is not done in identity()

array([[1, 0, 0, 0],
       [0, 1, 0, 0]])

In [ ]:
#4. Create a numpy with shape 2x5 that has all the elements as zero

In [ ]:
a = np.zeros((2,5), dtype = 'int')
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
a2 = np.full((2,5),0, dtype = 'int')
print(a2)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
#5. Create a numpy array that has the shape 3x5 and all the elemts are 5

In [ ]:
a3 = np.ones((3,5), dtype = 'int')*5
print(a3)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [ ]:
b2 = np.ones((15), dtype = 'int').reshape(3,5)*5
print(b2)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [ ]:
#6. Create a numpy array with random integers in the range of 0-100 and the sample size should be 25

In [ ]:
np.random.seed(100)     #seed - it will just fix the sequence on a specific number so data can not change
a= np.random.randint(0,101,25)
print(a)

array([71, 54, 24, 57, 49, 83, 83, 40, 19,  6, 18, 13, 90, 24, 27, 78, 85,
       59, 29, 44, 29,  0, 41, 89, 57])

In [ ]:
#7. Create a numpy array in the shape 2x3 with random integers in the range 0-100. Reshape the array in the shape 3x2 and print the updated shape of the resultant array.

In [ ]:
np.random.seed(1)
arr= np.random.randint(0,100, size = (2,3))
arr

array([[37, 12, 72],
       [ 9, 75,  5]])

In [ ]:
arr.shape

(2, 3)

In [ ]:
a1 = arr.reshape([3,2])
a1

array([[37, 12],
       [72,  9],
       [75,  5]])

In [ ]:
a1.shape

(3, 2)

In [ ]:
#8 Create a random array, with the range 0-1000, with a size 50 and step 2. Perform the following operations on the same.
a. Print the first ten elements of the array.
b. Print the last ten elements of the array.
c. Print the elements from the indexes 10-25.
d. Print the element at the index 22.
e. Print the array using negative indexing.
f. Print the last ten elements of the array, using negative indexing.

In [ ]:
#a. Print the first ten elements of the array.
a = np.arange(0, 1001, 2)
a

array([   0,    2,    4,    6,    8,   10,   12,   14,   16,   18,   20,
         22,   24,   26,   28,   30,   32,   34,   36,   38,   40,   42,
         44,   46,   48,   50,   52,   54,   56,   58,   60,   62,   64,
         66,   68,   70,   72,   74,   76,   78,   80,   82,   84,   86,
         88,   90,   92,   94,   96,   98,  100,  102,  104,  106,  108,
        110,  112,  114,  116,  118,  120,  122,  124,  126,  128,  130,
        132,  134,  136,  138,  140,  142,  144,  146,  148,  150,  152,
        154,  156,  158,  160,  162,  164,  166,  168,  170,  172,  174,
        176,  178,  180,  182,  184,  186,  188,  190,  192,  194,  196,
        198,  200,  202,  204,  206,  208,  210,  212,  214,  216,  218,
        220,  222,  224,  226,  228,  230,  232,  234,  236,  238,  240,
        242,  244,  246,  248,  250,  252,  254,  256,  258,  260,  262,
        264,  266,  268,  270,  272,  274,  276,  278,  280,  282,  284,
        286,  288,  290,  292,  294,  296,  298,  3

In [ ]:
a1= np.random.choice(a, size=50, replace = False)   #randomly pick the values from the choic of values you have given
sorta1 = np.sort(a1)

print('Array: ', sorta1)

Array:  [   8   16   64  144  146  156  166  176  182  198  202  262  266  278
  296  374  382  398  414  416  436  474  536  562  580  656  684  694
  710  720  728  734  736  744  758  778  784  788  794  826  828  830
  842  922  934  942  952  968  984 1000]


In [ ]:
#a. Print the first ten elements of the array.
print('First 10 elemts: ', sorta1[:10])

First 10 elemts:  [  8  16  64 144 146 156 166 176 182 198]


In [ ]:
#b. Print the last ten elements of the array.
print('Last 10 elemts: ', sorta1[-10 :])

#print('Last 10 elemts: ', sorta1[40 :])     if i am using +ve indexing number to get last 10 digit

Last 10 elemts:  [ 828  830  842  922  934  942  952  968  984 1000]


In [ ]:
#c. Print the elements from the indexes 10-25.
print('Elements from the indexes 10-25: ', sorta1[10:26])

Elements from the indexes 10-25:  [202 262 266 278 296 374 382 398 414 416 436 474 536 562 580 656]


In [ ]:
#d. Print the element at the index 22.
print('Element at the index 22: ', sorta1[22])

Element at the index 22:  536


In [ ]:
#e. Print the array using negative indexing.
print('Array using negative indexing: ', sorta1[::-1])

Array using negative indexing:  [1000  984  968  952  942  934  922  842  830  828  826  794  788  784
  778  758  744  736  734  728  720  710  694  684  656  580  562  536
  474  436  416  414  398  382  374  296  278  266  262  202  198  182
  176  166  156  146  144   64   16    8]


In [ ]:
#f. Print the last ten elements of the array, using negative indexing.
print('Array using negative indexing: ', sorta1[-10:])

Array using negative indexing:  [ 828  830  842  922  934  942  952  968  984 1000]


In [ ]:
#9. Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.
a. Insert the element 6 at the end of the array.
b. Insert the element 10 at the beginning of the array.
c. Insert the element 30, before 4.
d. Update the element 5 as 50.
e. Delete the element 50 in the updated array.
f. Create a function to search for the element 30.
g. Sort the array in ascending order

In [5]:
import numpy as np
arr= np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
#a. Insert the element 6 at the end of the array.
arr1 = np.append(arr,6)
arr1

array([1, 2, 3, 4, 5, 6])

In [11]:
#b. Insert the element 10 at the beginning of the array.
arr2 = np.insert(arr,0,10)            #(array, index, value)
arr2

array([10,  1,  2,  3,  4,  5])

In [46]:
#c. Insert the element 30, before 4.
arr = np.array([1, 2, 3, 4, 5])
index_4 = np.where(arr == 4)[0][0]
arr = np.insert(arr, index_4, 30)
arr

# arr == 4: Checks each element and returns True for the ones equal to 4.
# np.where(arr == 4): Finds the index (or indices) where that condition is True.
# [0][0]: This extracts the first matching index. (Just in case there are multiple 4s.)

array([ 1,  2,  3, 30,  4,  5])

In [50]:
#d. Update the element 5 as 50.
arr = np.array([1, 2, 3, 4, 5])
index_of_5 = np.where(arr == 5)[0][0]         #arr[arr == 5] = 50
arr[index_of_5] = 50

arr

array([ 1,  2,  3,  4, 50])

In [52]:
#e. Delete the element 50 in the updated array.
arr = np.array([1, 2, 3, 4, 50])
index_of_50 = np.where(arr == 50)[0][0]       #arr = arr[arr != 50]
arr = np.delete(arr, index_of_50)

arr

array([1, 2, 3, 4])

In [53]:
#f. Create a function to search for the element 30.
def search_element(array, value):
    if value in array:
        print(f"{value} found at index:", np.where(array == value)[0][0])
    else:
        print(f"{value} not found in the array.")

search_element(arr, 30)

30 not found in the array.


In [54]:
#g. Sort the array in ascending order
a = np.array([2,6,41,20,33,20])
arr = np.sort(a)

arr

array([ 2,  6, 20, 20, 33, 41])